language: python

before_install:
  - git clone -b feature https://github.com/esikachev/my-dev-ci-config 
  - pip install coveralls

services:
  - mysql

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=pep8
      sudo: required
    - python: 2.7
      env: TOX_ENV=py27
      sudo: required
    - python: 2.7
      env: TOX_ENV=functional
      sudo: required
    - python: 2.7
      env: TOX_ENV=cli
      sudo: required
    - python: 2.7
      env: TOX_ENV=cover
      sudo: required

script:
  - my-dev-ci-config/runner.sh

after_script:
  - if [ -f my-dev-server/my-dev-server-logs ]; then
      cat my-dev-server/my-dev-server-logs;
    fi
  - coveralls
