language: python

before_install:
  - git clone https://github.com/esikachev/my-dev-ci-config

services:
  - mysql

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=pep8
      sudo: required
    - python: 2.7
      env: TOX_ENV=py27
      sudo: required
    - python: 2.7
      env: TOX_ENV=functional
      sudo: required
    - python: 2.7
      env: TOX_ENV=cli
      sudo: required

script:
  - if [[ $TOX_ENV == 'cli' ]];
    then
      tox -e $TOX_ENV
    else
      my-dev-ci-config/runner.sh
    fi

after_script:
  - if [ -f my-dev-server/my-dev-server-logs ]; then
      cat my-dev-server/my-dev-server-logs;
    fi
